/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RPS;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Innocent Akash
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public int Ccount = 0 ;
    public int Pcount = 0 ;
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Plbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        Clbl = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 680));
        setMinimumSize(new java.awt.Dimension(850, 680));
        getContentPane().setLayout(null);

        Plbl.setFont(new java.awt.Font("Nerko One", 0, 30)); // NOI18N
        Plbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Plbl.setText("Player Wins : - 0");
        getContentPane().add(Plbl);
        Plbl.setBounds(90, 550, 660, 74);

        jLabel2.setFont(new java.awt.Font("Nerko One", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Let's Play Rock, Paper, Scissors !");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 30, 660, 74);

        jLabel3.setFont(new java.awt.Font("Nerko One", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Let's Play Rock, Paper, Scissors !");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 30, 660, 74);

        jLabel4.setFont(new java.awt.Font("Nerko One", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Play against the Computer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 100, 660, 74);

        jLabel5.setFont(new java.awt.Font("Nerko One", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Play against the Computer");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 100, 660, 74);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hand.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 270, 200, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hand-scissors--v2.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 270, 200, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hand-rock.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 270, 200, 200);

        jLabel6.setFont(new java.awt.Font("Nerko One", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Make Your Move");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 170, 660, 74);

        TF1.setEditable(false);
        TF1.setBackground(new java.awt.Color(255, 255, 255));
        TF1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(TF1);
        TF1.setBounds(40, 270, 200, 200);

        TF2.setEditable(false);
        TF2.setBackground(new java.awt.Color(255, 255, 255));
        TF2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(TF2);
        TF2.setBounds(320, 270, 200, 200);

        TF3.setEditable(false);
        TF3.setBackground(new java.awt.Color(255, 255, 255));
        TF3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(TF3);
        TF3.setBounds(580, 270, 200, 200);

        Clbl.setFont(new java.awt.Font("Nerko One", 0, 30)); // NOI18N
        Clbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clbl.setText("Computer Wins : - 0");
        getContentPane().add(Clbl);
        Clbl.setBounds(90, 500, 660, 74);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/White.jpg"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, -120, 1030, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
     TF2.setBackground( Color.decode("#686de0") );
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
       TF3.setBackground( Color.decode("#686de0") );
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
      TF1.setBackground( Color.decode("#686de0") );
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
      TF1.setBackground(Color.white);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
       TF2.setBackground(Color.white);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
       TF3.setBackground(Color.white);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       String Player = "R";
      RPSCode r = new RPSCode();
     int a = r.RPS(Player);
     
      if(a==0){
          Ccount++; 
                   JOptionPane.showMessageDialog(null, "Computer Wins ....!!");

      Clbl.setText("Computer Wins : - "+Ccount);
      }
      else
      {Pcount++;
      Plbl.setText("Player Wins : - "+Pcount);
      JOptionPane.showMessageDialog(null, "Player Wins ....!!");
      }
       
        
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       String Player = "P";
      RPSCode r = new RPSCode();
     int a = r.RPS(Player);
       if(a==0){
          Ccount++; 
                   JOptionPane.showMessageDialog(null, "Computer Wins ....!!");

      Clbl.setText("Computer Wins : - "+Ccount);
      }
      else
      {Pcount++;
      Plbl.setText("Player Wins : - "+Pcount);
      JOptionPane.showMessageDialog(null, "Player Wins ....!!");
      }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String Player = "S";
      RPSCode r = new RPSCode();
      
     int a = r.RPS(Player);
       if(a==0){
          Ccount++; 
                   JOptionPane.showMessageDialog(null, "Computer Wins ....!!");

      Clbl.setText("Computer Wins : - "+Ccount);
      }
      else
      {Pcount++;
      Plbl.setText("Player Wins : - "+Pcount);
      JOptionPane.showMessageDialog(null, "Player Wins ....!!");
      }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Clbl;
    private javax.swing.JLabel Plbl;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
